#!/bin/bash

## Dump a wordpress db automatically
## Used in maintaining a development and production environment for Wordpress
## deployments
## Author Andy O'Neill <oneill@energyhub.net>

DUMP_FILE=db/dump.sql
DB_USER=wordpress
DB_PASSWORD=wordpress

if [ ! -e wp-config.php ]; then
	echo "wp-config.php not found"
	echo "Run from your wordpress directory"
	echo "Usage dumpdb"
	exit 1
fi
DB_NAME=$(grep DB_NAME wp-config.php  | awk -F "'" '{print $4}')

mkdir -p db

echo "Dumping $DB_NAME to $DUMP_FILE"
mysqldump --opt -u$DB_USER -p$DB_PASSWORD --databases $DB_NAME > $DUMP_FILE

echo "Dumped $DB_NAME to $DUMP_FILE"

