#!/bin/bash
set -eu

## Load a wordpress dumped db
## Used in maintaining a development and production environment for Wordpress
## deployments
## Author Andy O'Neill <oneill@energyhub.net>


DB_DUMP=db/dump.sql

# Get the name of the database that was dumped
DUMP_DB_NAME=$(grep "CREATE DATABASE" $DB_DUMP | awk -F '`' '{print $2}')
# Get the parameters of the db to load into from wp_config.php
DB_NAME=$(      grep DB_NAME        wp-config.php  | awk -F "'" '{print $4}')
DB_USER=$(    	grep DB_USER 	    wp-config.php  | awk -F "'" '{print $4}')
DB_PASSWORD=$(  grep DB_PASSWORD    wp-config.php  | awk -F "'" '{print $4}')
DB_HOST=$(      grep DB_HOST        wp-config.php  | awk -F "'" '{print $4}' |  awk -F ":" '{print $1}' )
DB_PORT=$(      grep DB_HOST        wp-config.php  | awk -F "'" '{print $4}' |  awk -F ":" '{print $2}' )
echo "DB_NAME=[$DB_NAME]"
echo "DB_USER=[$DB_USER]"
echo "DB_PASSWORD=[$DB_PASSWORD]"
echo "DB_HOST=[$DB_HOST]"
echo "DB_PORT=[$DB_PORT]"
#TODO add check for port presence

DATE=$(date +%Y-%m-%d-%H%M)
BACKUP_FILE=db/$DB_NAME.${DATE}.sql

if [ ! -e $DB_DUMP ]; then
	echo "DB to load file not found: $DB_DUMP"
	echo "Run from your wordpress directory"
	echo "Usage loaddb"
	exit 1
fi

echo "Loading from $DB_DUMP to $DB_NAME."
echo "Replacing database name in dump $DUMP_DB_NAME to $DB_NAME."

echo "Making backup of $DB_NAME to $BACKUP_FILE"
mysqldump --opt -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD --databases $DB_NAME > $BACKUP_FILE

echo "Loading dump into $DB_NAME"
cat $DB_DUMP | sed "s/$DUMP_DB_NAME/$DB_NAME/" \
        | mysql -h$DB_HOST -P$DB_PORT -u$DB_USER -p$DB_PASSWORD $DB_NAME
